### ISSUE TITLE
post content를 검색할 때 (아마 html 태그들이 검색돼서) 엉뚱한 결과가 나옴

### ISSUE THREAD

**Issue by YujinGaya** [sparcs-kaist/new-ara-api#15]
검색어를 `r`로 해서 검색했을 때 많은 글이 나온다는 사실을 @ojh3636 님이 레포트해주셨습니다. 한 번 확인해주시겠어요? @talkwithraon

**Comment by talkwithraon** [comment]
#40 으로 일단 해결. json의 경우에는 추가적인 작업을 진행해야 함

**Comment by apple12347678** [comment]
에디터가 quill에서 tiptap으로 변경되어 닫을게요 @jwoo0122
