### ISSUE TITLE
SPARCS SSO 방식 외에 다른 방식의 인증 과정을 제공

### ISSUE THREAD

**Issue by i-am-kangin** [sparcs-kaist/new-ara-api#19]
학내 업체 등에 계정을 제공하기 위해서 SPARCS SSO 방식 외에 다른 방식의 인증 과정을 제공 해야 함.

로그인 및 로그아웃 기능을 최우선적으로 제공하고, 가능하다면 비밀번호 변경 등의 기능을 제공 할 수 있게 함.

**Comment by talkwithraon** [comment]
issue-19-support-for-none-sparcs-sso-users 으로 해결됨

**Comment by apple12347678** [comment]
인증 방식이 완전히 바뀜에 따라 새로 작업하도록 하겠습니다
