### ISSUE TITLE
익명 게시판의 경우 JSON Response 익명화

### ISSUE THREAD

**Issue by jessyoon14** [sparcs-kaist/new-ara-api#196]
익명 게시판의 글 / 댓글의 경우, JSON Response에 사용자 ID, Username을 익명화해서 보냅니다.
article id / comment id를 seed로 하고 id를 랜덤으로 맞춘 후, 그 랜덤 id를 기반으로 Username을 정해서 보냅니다.

**Comment by jungnoh** [comment]
랜덤으로 하면 그걸 또 저장해야 해서, 대신 deterministic한 방법을 사용하면 좋을 것 같아요.
Article ID + User ID 에다 secret 값을 하나 섞어서 해쉬한 값을 이용하면 어떨까요?

**Comment by jessyoon14** [comment]
좋은 것 같아요. 그렇게 해볼게요~ 감사합니다
