### ISSUE TITLE
다른 사용자의 게시글 목록을 불러올 때, 익명 게시글 제외

### ISSUE THREAD

**Issue by jessyoon14** [sparcs-kaist/new-ara-api#216]
마이페이지에서 내가 쓴 글을 볼때, 그리고 게시글에서 작성자 이름을 클릭해서 그 작성자의 모든 글을 볼때 아래 api를 사용합니다:
`api/articles/?created_by=1`

다른 사용자의 글 목록을 조회할 때는 익명 게시글이 보이지 않고, 자신의 작성 글 목록에는 자신이 작성한 익명 게시글들이 보이도록 수정하였습니다.

**Comment by jungnoh** [comment]
@jessyoon14 가 해결된거래요
