### ISSUE TITLE
스크랩한 게시글 스크랩 취소시에도 side_article에 남아있는 오류 수정

### ISSUE THREAD

**Issue by xhaktm3** [sparcs-kaist/new-ara-api#228]
자세한 버그 리포트는 아래 노션을 참고해주세요.
https://www.notion.so/sparcs/side_articles-1ec72349d9be4734ae601a929211f510

**Comment by victory-jooyon** [comment]
위 노션 링크는 무한루프에 대한 버그 리포트 같은데, 스크랩 취소에 대한 버그리포트로 링크 수정 부탁드릴게요.

**Comment by jungnoh** [comment]
Fixed in #231
