### ISSUE TITLE
TestCase 작성

### ISSUE THREAD

**Issue by i-am-kangin** [sparcs-kaist/new-ara-api#23]
permission 등의 테스트를 진행하기 위해, 또한 live 시에 기능 추가를 원활히 하기 위해 TestCase의 작성이 필요함.

**Comment by apple12347678** [comment]
장고 테스트 쓸 줄 아시는 분 구합니다

**Comment by victory-jooyon** [comment]
https://github.com/sparcs-kaist/new-ara-api/tree/master/tests
