### ISSUE TITLE
댓글에 대하여 숨김처리 통일

### ISSUE THREAD

**Issue by jessyoon14** [sparcs-kaist/new-ara-api#252]
jungnoh님의 PR #247 에서, 게시글에 대한 숨김처리가 통일되었습니다.

이 이슈에서는, 댓글에 대한 숨김처리도 같은 로직으로 통일합니다.
아래는 위 PR 내용을 댓글에 맞게 변형한 것입니다:

# 주요 수정사항
- `hidden_content` 필드 삭제 (참고: 숨겨진 상태일 경우 `content`는 null)
- `string[]` 타입의 `why_hidden` 필드를 추가하여 숨겨진 이유들에 대한 목록을 반환 (값은 하단 참고)
- 숨겨진 내용을 보고자 할 때에는 query에 `override_hidden` 키를 주면 됨
- 숨겨진 내용을 볼 수 있는지 (cf. 신고로 숨겨진 글은 숨기기를 풀 수 없음) 여부는 `can_override_hidden` 값을 반환
  애초에 숨겨지지 않았던 게시물은 `can_override_hidden`이 null임.

참고) 숨겨진 댓글을 보더라도 why_hidden은 유지되기 때문에 원래부터 볼 수 있는 글인지, override한 글인지 응답 내용으로 구분이 가능

# why_hidden 값
- `REPORETED_CONTENT`
- `BLOCKED_USER_CONTENT`
- `DELETED_CONTENT`  >  커멘트 모델에서는 삭제된 메세지들도 우선 가져온다음 히든처리함.

@xhaktm3

**Comment by xhaktm3** [comment]
전체적인 로직은 #247 과 같습니다.
