### ISSUE TITLE
Read-only 게시판과 일부 사용자의 write 권한 부여

### ISSUE THREAD

**Issue by talkwithraon** [sparcs-kaist/new-ara-api#27]
제곧내

**Comment by apple12347678** [comment]
Django groups와 permissions를 사용하여 다양한 역할을 규정할 필요가 있을 듯합니다. 총학 등 non SSO 사용자들이 공지나 관리를 편하게 하려면 django admin과 별도의 admin 프론트와 non SSO 지원 등도 필요할 것으로 보입니다.

**Comment by victory-jooyon** [comment]
완료
