### ISSUE TITLE
Collector 재작성 필요.

### ISSUE THREAD

**Issue by i-am-kangin** [sparcs-kaist/new-ara-api#29]
현재 특정 db row 삭제 시에 관계 되어 있는(foreign key, o2o field, m2m field) row가 삭제되지 않음.

**Comment by apple12347678** [comment]
@talkwithraon 장고 2.0 이상으로 마이그레이션하면서 foreign key 필드들에 on_delete를 반드시 추가하도록 변경되었는데, 일단 얘를 전부 models.CASCADE로 설정해놨습니다. 그런데 실제로 이 옵션이 관계된 row를 삭제하는지는 확인해보지 않았는데 혹시 알아봐주실 수 있나요?
