### ISSUE TITLE
Better XSS Sanitizing

### ISSUE THREAD

**Issue by apple12347678** [sparcs-kaist/new-ara-api#50]
tiptap이 생성한 json을 iterate하면서 XSS 검사를 해야 함 (인젝션 가능)

**Comment by apple12347678** [comment]
#43

**Comment by apple12347678** [comment]
Frontend 쪽에 pure HTML로 보낼 것으로 전달함 - bleach 이용해 sanitize 할것

**Comment by victory-jooyon** [comment]
완료. https://github.com/sparcs-kaist/new-ara-api/blob/master/ara/sanitizer.py
