### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by sni-J** [sparcs-kaist/new-ara-api#59]
```apps/core/models/article.py```: Integrity Error -> 500 Error

같은 파일에서 sanitize에 걸리면 400을 띄우는 게 맞을 듯 하여
```
from rest_framework import status, response
...
return response.response(status=status.HTTP_400_BAD_REQUEST)
``` 
로 일단 구현 중인데, 해당 부분은 model이 아니라 view로 들어가는 것이 맞다고 생각됨

아무튼 전체적인 에러 핸들링이 필요한 것 같아요

**Comment by apple12347678** [comment]
HTTP status와 message를 파라미터로 받는 일반적인 throwable 하나 만들어서 여기저기 돌려 쓰면 될 것 같습니다. npm의 http-errors처럼..

**Comment by victory-jooyon** [comment]
integrity error 관련해서는 serializer쪽에서 잡아서 대부분 i18n으로 에러메시지 내려주었습니다.
아는 범위 내에서는 500 에러가 나지 않도록 했습니다.
