### ISSUE TITLE
python 의존성 관리 도구 추가

### ISSUE THREAD

**Issue by talkwithraon** [sparcs-kaist/new-ara-api#61]
python 의존성 관리 도구인 pipenv 혹은 poetry를 추가했으면 좋겠습니다.

참고할 만한 글입니다. https://johnfraney.ca/posts/2019/03/06/pipenv-poetry-benchmarks-ergonomics/

**Comment by talkwithraon** [comment]
requirements.txt 뜯어보면서 어떤 의존성이 직접적으로 설치된 의존성이고 어떤 의존성이 전자로 인해 간접적으로 설치된 의존성인지 고민했는데 상당히 어렵네요. 얘는 베타 이후에 해도 괜찮을 거 같습니다.

**Comment by apple12347678** [comment]
점점 requirements가 난잡해져 이것부터 정리하겠습니다. 현재 코드가 안쓰고 있는 패키지들 전부 쳐낸 후(celery 등)

1. 현재 코드가 작동하도록
2. dev와 prod 디펜던시가 구분되도록

분리해 보겠습니다.
