### ISSUE TITLE
에러 트래킹 도구 추가

### ISSUE THREAD

**Issue by talkwithraon** [sparcs-kaist/new-ara-api#62]
New Relic 이나 Sentry 같은 Error Tracking Tool 을 추가했으면 좋겠습니다.

아래는 대략적인 비교입니다.

https://stackshare.io/stackups/new-relic-vs-sentry

가볍게 Sentry 연동만 해놓는 것으로 충분할 것 같다고 생각하고 있기는 하고 있습니다. Frontend 쪽도 Sentry 연동을 해놓으면 좋을듯 합니다.

**Comment by apple12347678** [comment]
#26 중복인것 같습니다..
