### ISSUE TITLE
Directory 구조 변경

### ISSUE THREAD

**Issue by talkwithraon** [sparcs-kaist/new-ara-api#64]
루트 디렉토리 아래에 ara 디렉토리가 있고, 그 안에 코드들이 있는 형태인데 
ara 디렉토리 안에 있는 내용들이 루트 디렉토리 내에 존재하는 것이 좀 더 일반적인 방식인 듯 합니다.
변경하는 것이 많이 힘들지는 않으니 특별한 이유가 없으면 바깥으로 빼면 좋을 듯 합니다.

**Comment by talkwithraon** [comment]
https://github.com/sparcs-kaist/new-ara-api/commit/10cc58633e26ef9494cd9a462387adb59f71e360

**Comment by apple12347678** [comment]
확인했습니다
