### ISSUE TITLE
Automatic Deployment

### ISSUE THREAD

**Issue by apple12347678** [sparcs-kaist/new-ara-api#68]
* [ ] DB 시드 생성
* [ ] 환경변수 존재 시 superuser 생성
* [x] docker-compose.yml 작성 (다른 repo로 분리될 수 있음)
* [ ] github actions 등 사용하여 release 브랜치 merge마다 코드 자동 업데이트 & DB 마이그레이션

**Comment by apple12347678** [comment]
[docker compose repo](https://github.com/sparcs-kaist/docker-new-ara-api)

**Comment by talkwithraon** [comment]
api, web, db 를 한 번에 다 띄워주고 초기화도 시켜주는 docker-compose.yml 도 하나 있으면 좋겠다 생각이 들었습니다. 새로 들어오는 개발자가 환경 세팅하기 편할 거 같아서요. 언젠가 한 번 해보겠습니다. 다음 학기 개발자 들어오기 전까지만 하면 되니...

**Comment by talkwithraon** [comment]
database seeding 용 initialization script 작성도 여기에 넣어놓을까요

**Comment by apple12347678** [comment]
시딩은 보통 초기 한번 필요하긴 한데 이미 셋업된 환경에서 밀고 다시 만들고 할 일도 많으니까 이 레포에 쓰는게 맞지 않을까 싶습니다.

**Comment by victory-jooyon** [comment]
docker-compose.yml 은 s3의 credentials 버킷에.
aws codebuild로 이미지 빌드 -> 테스트 -> 이미지 태그 -> 이미지 푸시 까지 자동화완료.
