### ISSUE TITLE
Setup profiling tools for optimizing invocation time

### ISSUE THREAD

**Issue by i-am-kangin** [sparcs-kaist/new-ara-api#73]
django-reversion 을 적용하여, list action 에서 속도가 저하되는 부분이 많을 것 같습니다. created_at이나 updated_at을 추가적인 쿼리를 해서 가져와야 하기 때문입니다.

특히 많이 느린 부분에 대해서 우선적으로 쿼리 최적화를 진행하면 좋을탠데
drf-tracking(느린 순으로 정렬해서 보기) 이나 django-silk(대략적인 통계) 같은 최소한의 툴을 부착할 수 있으면 좋겠습니다.

허락을!

각각의 링크는 아래에

https://github.com/aschn/drf-tracking
https://github.com/jazzband/django-silk

**Comment by apple12347678** [comment]
대환영입니다 :) 저도 결과가 궁금하네요

**Comment by victory-jooyon** [comment]
django silk는 붙였다가 다시 뗀 상태. 필요시 https://github.com/sparcs-kaist/new-ara-api/pull/92 참고.

**Comment by jungnoh** [comment]
지속적으로 개선중, 단일 이슈로 계속되어야 할 사항은 아닌듯 하여 닫습니다.
